language: php
php:
  - 5.4
# execute any number of scripts before the test run, custom env's are available as variables
before_script:
  - mysql -uroot < felec.sql
  
# omitting "script:" will default to phpunit
# use the $DB env variable to determine the phpunit.xml to use
script: phpunit --stderr --configuration phpunit.xml --coverage-text
